print("part A of programming get done.")
print("part B of programming get done.")
print("part C of programming get done.")
print("part D of programming get done.")
print("part E of programming get done.")